// Generated by CoffeeScript 1.7.1
angular.module('uiTestingangularApp.controllers', []);

angular.module('uiTestingangularApp.directives', []);

angular.module('uiTestingangularApp.services', []);

angular.module('uiTestingangularApp.filters', []);
